services:
  app-backend:
    user: root
    build:
      context: ./app-backend
    container_name: app-backend
    restart: always
    ports:
      - "5090:9000"
    volumes:
      - ./app-backend:/var/www
      - /var/www/vendor
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile.prod
    container_name: frontend
    restart: always
    ports:
      - "5300:3000"
    # volumes:
    #   - ./frontend:/app
    #   - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - FAST_REFRESH=false
      - WATCHPACK_POLLING=true 
    networks:
      - app-network
    # command: npm start

  frontend-admin:
    build:
      context: ./frontend-admin
    container_name: frontend-admin
    restart: always
    ports:
      - "5301:3001"
    volumes:
      - ./frontend-admin:/app
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true
    networks:
      - app-network
    command: npm run dev

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - "5003:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app-backend
      - frontend
      - frontend-admin
      - postgres
      - langchain
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  langchain:
    build:
      context: ./langchain
      dockerfile: Dockerfile
    container_name: langchain
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=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
      - LANGCHAIN_PROJECT=pr-smug-warfare-80
    ports:
      - "5400:4000"
    volumes:
      - ./langchain:/app
    depends_on:
      - app-backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  pgdata: